name: build

on: [workflow_dispatch, push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Linux build dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update -y
          sudo apt install -y build-essential gnome-keyring

      - name: Fetch head
        uses: actions/checkout@v4

      - name: Install Rust Toolchain (stable)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Build (debug)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --all-targets

      - name: Linux tests
        if: matrix.os == 'ubuntu-latest'
        run: dbus-run-session -- bash linux-test.sh

      - name: Non-linux tests
        if: matrix.os != 'ubuntu-latest'
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose

      - name: Format check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Clippy check
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
